// Studio Varaždin — Project Data
// Each project maps to a "film" card on the website

const PROJECTS = [
  {
    id: "advent-varazdin-2024",
    title: "Advent u Varaždinu",
    subtitle: "Aftermovie 2024",
    year: 2024,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Festival Aftermovie",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/advent u varazdinu.webp",
    heroImage: "assets/images/advent u varazdinu.webp",
    themeColor: "hsl(205, 55%, 20%)",
    tagline: "Where winter warmth outshines the cold.",
    description: "The official aftermovie for the multi-award-winning Advent u Varaždinu 2024. Capturing the singular magic of Croatia's most romantic winter destination, the film weaves through glowing baroque streets, the kinetic energy of the Advent Lift, and the genuine warmth of a city in celebration. A cinematic postcard of light and laughter.",
    awards: [],
    featured: false,
    badges: ["Christmas", "Aftermovie", "Destination Film"],
    youtubeUrl: "https://www.youtube.com/watch?v=1HRTf8t3RQo"
  },
  {
    id: "rimac-fpv",
    title: "Rimac Automobili",
    subtitle: "One-Take FPV Tour",
    year: 2024,
    client: "Rimac Automobili",
    category: "immersive",
    type: "FPV Drone Tour",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "FPV Drone Team"],
    thumbnail: "assets/images/rimac.webp",
    heroImage: "assets/images/rimac.webp",
    themeColor: "hsl(215, 60%, 15%)",
    tagline: "Precision built for the edge of the impossible.",
    description: "An adrenaline-fueled, single-take FPV drone flight through the heart of Rimac Automobili. Weaving through hypercar assembly lines, engineering labs, and production halls, the film captures the relentless energy and technological precision of Croatia's automotive future in one unbroken, cinematic movement.",
    awards: [],
    featured: false,
    badges: ["FPV", "One-Take", "Hypercar"],
    youtubeUrl: "https://www.youtube.com/watch?v=UhCaWGTM69o"
  },
  {
    id: "castles-2025",
    title: "100 Dvoraca Sjevera Hrvatske",
    subtitle: "A Fairytale Film",
    year: 2025,
    client: "Castle Network of Northern Croatia",
    category: "short-film",
    type: "Cinematic Short / Drama",
    duration: "~15 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Full cast & crew"],
    thumbnail: "assets/images/100 dvoraca sjevera hrvatske.webp",
    heroImage: "assets/images/100 dvoraca sjevera hrvatske.webp",
    themeColor: "hsl(40, 55%, 18%)",
    tagline: "Every page turns a legend into life.",
    description: "A fairytale-structured short film following ten-year-old Ema and her mother as a magical pop-up book transports them into the love stories of northern Croatia's castles. At Trakošćan, a knight rides off to war; at Veliki Tabor, a feudal lord falls for a peasant girl; at the Varaždin citadel, time defeats a love too patient to survive it; at Čakovec, a family's warmth fills the courtyard with mud and laughter.",
    awards: [],
    featured: true,
    badges: ["Fairytale Drama", "Castles", "2025"],
    youtubeUrl: "https://www.youtube.com/watch?v=FzO1Pa5Tf30"
  },
  {
    id: "vudrag-dubai-2025",
    title: "Build the Impossible",
    subtitle: "VUDRAG × Dubai",
    year: 2025,
    client: "Nikola Vudrag / Studio Varaždin",
    category: "documentary",
    type: "Cinematic Art Film",
    duration: "~3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/Build the impossible.webp",
    heroImage: "assets/images/Build the impossible.webp",
    themeColor: "hsl(15, 65%, 18%)",
    tagline: "From red iron to impossible skylines.",
    description: "A cinematic exploration of Dubai framed through a lens of artistic defiance and infinite potential. The film begins with the raw, red iron of sculptor Nikola Vudrag's workshop — the same hands that forge art from fire now stand before the world's most ambitious skyline. A meditation on ambition, craft, and what happens when a maker's vision meets a city that dares to dream beyond limits.",
    awards: [],
    featured: true,
    badges: ["Art Film", "Dubai", "VUDRAG"],
    youtubeUrl: "https://www.youtube.com/watch?v=7-uhfMFcx7Y"
  },
  {
    id: "irma-dora-2026",
    title: "Ni Traga",
    subtitle: "Irma — DORA 2026",
    year: 2026,
    client: "Irma / HRT DORA",
    category: "music-video",
    type: "Music Video — Contest Entry",
    duration: "~3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Jan Jakovljev", "Anja Grabovac", "Hrvoje Domazet"],
    thumbnail: "assets/images/irma ni traga.webp",
    heroImage: "assets/images/irma ni traga.webp",
    themeColor: "hsl(270, 40%, 16%)",
    tagline: "Disappear. Leave no trace. Only the song remains.",
    description: "The official music video for Irma's DORA 2026 entry — Croatia's national selection for Eurovision. 'Ni Traga' (No Trace) is a haunting, atmospheric performance piece that dissolves the line between presence and absence. Written by Jan Jakovljev and Anja Grabovac, arranged by Hrvoje Domazet, and directed by Studio Varaždin with a visual language of shadow, breath, and disappearance.",
    awards: ["DORA 2026 Selection"],
    featured: true,
    badges: ["DORA 2026", "Eurovision", "Music Video"],
    youtubeUrl: "https://www.youtube.com/watch?v=4RWmJPF_L_c"
  },
  {
    id: "dvorista-sjevera-2025",
    title: "Dvorišta Sjevera",
    subtitle: "Courtyards of the North",
    year: 2025,
    client: "Varaždinska Županija",
    category: "documentary",
    type: "Destination Film",
    duration: "~5 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/festival dvorista.webp",
    heroImage: "assets/images/festival dvorista.webp",
    themeColor: "hsl(145, 35%, 15%)",
    tagline: "Behind every gate, a world waits.",
    description: "A cinematic portrait of northern Croatia's hidden courtyards — the intimate, sun-dappled spaces behind baroque façades where real life breathes. The film drifts through stone archways, past climbing vines and weathered benches, revealing the private geographies of a region that keeps its warmest moments behind closed doors. A gentle, poetic celebration of architecture as memory.",
    awards: [],
    featured: false,
    badges: ["Destination Film", "Heritage", "Courtyards"],
    youtubeUrl: "https://www.youtube.com/watch?v=PtGE0iucmyA"
  },
  {
    id: "mint-2024",
    title: "Hrvatska Kovnica Novca",
    subtitle: "30 Years — Anniversary Film",
    year: 2024,
    client: "Hrvatska Kovnica Novca",
    category: "institutional",
    type: "Institutional Documentary",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/kovnica novca.webp",
    heroImage: "assets/images/kovnica novca.webp",
    themeColor: "hsl(43, 75%, 22%)",
    tagline: "Every coin is a piece of history, struck for eternity.",
    description: "A prestigious production for Croatia's national mint — celebrating 30 years of minting excellence. A story film spanning past, present, and future, produced with original score composition, professional narration, and custom VFX/CGI sequences. The film treats coin-minting as an act of national memory-keeping, giving weight and emotional resonance to limited-edition Euro and commemorative coin collections.",
    awards: [],
    featured: false,
    badges: ["National Institution", "30th Anniversary", "VFX/CGI"],
    youtubeUrl: "https://www.youtube.com/watch?v=8aq_M_negfw"
  },
  {
    id: "advent-sonica-2025",
    title: "Saonice Djeda Mraza",
    subtitle: "Advent u Varaždinu — Teaser 2025",
    year: 2025,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Event Teaser / Trailer",
    duration: "~1 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/advent saonice.webp",
    heroImage: "assets/images/advent saonice.webp",
    themeColor: "hsl(210, 55%, 14%)",
    tagline: "The sleigh bells are getting louder.",
    description: "A cinematic teaser announcing the return of Advent u Varaždinu 2025 — this time featuring Santa's Sleigh, a new immersive attraction. Snow drifts through baroque streets, lanterns glow in deep blue twilight, and the distant sound of sleigh bells cuts through the silence. A promise of magic, compressed into a single breathless minute.",
    awards: [],
    featured: false,
    badges: ["Christmas", "Teaser", "Advent 2025"],
    youtubeUrl: "https://www.youtube.com/watch?v=q5yFBLhhfAo"
  },
  {
    id: "stefany-eden-2025",
    title: "Eden",
    subtitle: "Music Video — Stefany",
    year: 2025,
    client: "Stefany",
    category: "music-video",
    type: "Music Video",
    duration: "~3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Jan Jakovljev", "Anja Grabovac", "Oryng"],
    thumbnail: "assets/images/eden stefani.webp",
    heroImage: "assets/images/eden stefani.webp",
    themeColor: "hsl(160, 45%, 14%)",
    tagline: "Paradise found. Paradise fractured.",
    description: "The second visual chapter in the Stefany universe. 'Eden' trades the crimson tension of 'Otrov i Med' for lush, garden-soaked imagery — a paradise where beauty and danger entwine like vines. Produced by Oryng (Franko Štrbac, Borna Ledić, Marin Benja) with music by Jan Jakovljev and Anja Grabovac, the film layered botanical surrealism and choreographed light to create an intoxicating visual dreamscape.",
    awards: [],
    featured: false,
    badges: ["Music Video", "Visual Sequel", "2025"],
    youtubeUrl: "https://www.youtube.com/watch?v=fGVweDW6n-8"
  },
  {
    id: "stare-fotke-2025",
    title: "Oživljene Fotografije",
    subtitle: "AI-Revived Varaždin Archives",
    year: 2025,
    client: "Varaždin Tourist Board / Studio Varaždin",
    category: "short-film",
    type: "AI-Augmented Heritage Film",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/varazdin kao nekad.webp",
    heroImage: "assets/images/varazdin kao nekad.webp",
    themeColor: "hsl(35, 50%, 16%)",
    tagline: "The past blinks its eyes open.",
    description: "A groundbreaking experiment in AI-augmented historical storytelling. Archival photographs of old Varaždin — sepia-toned streets, market squares, faces from a century ago — are brought to life using generative AI animation. What was frozen now breathes: heads turn, leaves rustle, horses pull carts through cobbled streets. The result is uncanny, beautiful, and deeply nostalgic — a city remembering itself.",
    awards: [],
    featured: false,
    badges: ["AI-Augmented", "Heritage", "Archives"],
    youtubeUrl: "https://www.youtube.com/watch?v=5PHUKGlNnSA"
  },
  {
    id: "trakostyan-2025",
    title: "Glasnik Vječnosti",
    subtitle: "Let u Prošlost — Trakostyan Tours",
    year: 2025,
    client: "Trakostyan-Tours",
    category: "short-film",
    type: "Historical Cinematic Short",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "15+ period performers", "Live falcon & falconer"],
    thumbnail: "assets/images/let u proslost.webp",
    heroImage: "assets/images/let u proslost.webp",
    themeColor: "hsl(148, 38%, 10%)",
    tagline: "Kingdoms fall. Stories endure.",
    description: "Three eras. Three locations. One eternal witness. Glasnik Vječnosti (Messenger of Eternity) weaves Roman mythology, medieval intrigue, and baroque court drama through the thread of a falcon's flight — from the ruins of Varaždinske Toplice to the towers of Trakošćan castle to the baroque skyline of Varaždin. A flight into the past — falconry with the great figures of history through the myths and legends of northwestern Croatia.",
    awards: ["Tourism Film of the Year Nomination"],
    featured: true,
    badges: ["Epic Historical", "3 Eras", "Live Falcon"],
    youtubeUrl: "https://www.youtube.com/watch?v=1otqcVn3ZO4"
  },
  {
    id: "foi-promo-2024",
    title: "FOI — Fakultet Budućnosti",
    subtitle: "Faculty of Organisation & Informatics",
    year: 2024,
    client: "FOI / University of Zagreb",
    category: "institutional",
    type: "Cinematic Promo Film",
    duration: "~3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/foi.webp",
    heroImage: "assets/images/foi.webp",
    themeColor: "hsl(215, 50%, 16%)",
    tagline: "Knowledge moves. The future follows.",
    description: "A cinematic-grade promotional film for the Faculty of Organisation and Informatics (FOI) in Varaždin — one of Croatia's most forward-thinking university institutions. The film captures the intellectual energy of a campus where code, design, and data science collide. Shot with cinematic precision, it frames academia not as a lecture hall but as a living ecosystem of ambition, innovation, and youth in motion.",
    awards: [],
    featured: false,
    badges: ["University", "Cinematic Promo", "FOI"],
    youtubeUrl: "https://www.youtube.com/watch?v=rIy1way8S_I"
  },
  {
    id: "ivanec-legende-2025",
    title: "Ivanec — Legende i Priče",
    subtitle: "629th Anniversary Historical Film",
    year: 2025,
    client: "Grad Ivanec",
    category: "documentary",
    type: "Historical Documentary",
    duration: "~8 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Ljiljana Risek (script)", "Kristijan Petrović (narrator)"],
    thumbnail: "assets/images/Ivenc cover.webp",
    heroImage: "assets/images/Ivenc cover.webp",
    themeColor: "hsl(145, 40%, 14%)",
    tagline: "Every mountain holds a story older than its name.",
    description: "A historical film celebrating Ivanec's 629th anniversary — a cinematic journey through the legends and stories woven into the landscape of Ivanščica mountain. From ancient Roman traces to Slavic forest spirits and medieval ruins, the film weaves AI-generated matte paintings, orthomosaic archaeological reconstructions, and FPV drone poetry into a deeply literary portrait. Directed by young Varaždin filmmaker Timon Terzić with a screenplay by Ljiljana Risek.",
    awards: [],
    featured: false,
    badges: ["Historical", "629th Anniversary", "Legends"],
    youtubeUrl: "https://www.youtube.com/watch?v=PMn6eKhktGc"
  },
  // ── Projects without YouTube links (existing portfolio) ──
  {
    id: "spancirfest-2023",
    title: "Špancirfest",
    subtitle: "25th Anniversary Aftermovie",
    year: 2023,
    client: "Varaždin Tourist Board",
    category: "festival",
    type: "Festival Aftermovie",
    duration: "7 min",
    director: "Timon Terzić",
    team: ["Dario Mikulek", "Dorian Domiter", "Sven Danko", "Ivica Hozmec", "Luka Ivić", "Stella Grbec"],
    thumbnail: "assets/images/spancirfest.png",
    heroImage: "assets/images/spancirfest.png",
    themeColor: "hsl(38, 70%, 25%)",
    tagline: "A city. Ten days. Four stories.",
    description: "For the 25th anniversary of Croatia's largest street festival, Studio Varaždin crafted a seven-minute multi-narrative cinematic experience. Four interlocking human stories — a lost child, a sketching artist, a young couple, a street musician — unfold against the baroque splendour of Varaždin. The festival itself becomes a fifth protagonist, alive with butterfly ornaments, fire performers, and the electric energy of a city in celebration.",
    awards: ["Festival Special Commission"],
    featured: false,
    badges: ["25th Edition", "Multi-Narrative", "Festival Film"],
    youtubeUrl: null
  },
  {
    id: "advent-varazdin-2023",
    title: "Advent u Varaždinu",
    subtitle: "Christmas City Film",
    year: 2023,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Destination Film",
    duration: "3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/advent-varazdin.png",
    heroImage: "assets/images/advent-varazdin.png",
    themeColor: "hsl(200, 45%, 18%)",
    tagline: "A letter to Santa. A city that writes back.",
    description: "A cinematic destination film for Varaždin's multi-award-winning Christmas market, told through a child's searching letter to Santa Claus. As lanterns glow and snowflakes fall over the baroque city, the narration asks whether magic is still real — and the city's warmth answers. One of northern Croatia's most emotionally resonant pieces of destination content.",
    awards: ["Best Christmas Destination Content"],
    featured: false,
    badges: ["Award-Winning Market", "Christmas", "Destination Film"],
    youtubeUrl: null
  },
  {
    id: "vudrag-zeiss-2024",
    title: "VUDRAG × ZEISS",
    subtitle: "Sessions: Maker Portrait",
    year: 2024,
    client: "Zeiss Industrial Quality Solutions",
    category: "documentary",
    type: "Documentary Portrait",
    duration: "3:20 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/vudrag zeiss.webp",
    heroImage: "assets/images/vudrag zeiss.webp",
    themeColor: "hsl(30, 60%, 20%)",
    tagline: "Metal is more than material. It's life forged in fire.",
    description: "A prestige co-production with Zeiss Industrial Quality Solutions for their global Maker Portrait series. The film follows Croatian sculptor Nikola Vudrag from sketching table to fire-lit workshop to precision 3D scanning — a meditation on the relationship between brute force and delicate technology, and the enduring question of legacy. Shot with ZEISS cinema glass to international production standards.",
    awards: ["International Co-Production"],
    featured: false,
    badges: ["ZEISS Partnership", "Documentary", "International"],
    youtubeUrl: null
  },
  {
    id: "advent-lift-2024",
    title: "The Advent Lift",
    subtitle: "Journey to the North Pole",
    year: 2024,
    client: "Varaždin Tourist Board",
    category: "immersive",
    type: "Immersive Physical Experience",
    duration: "3 min live",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Hrvoje Hegedušić"],
    thumbnail: "assets/images/advent-lift.png",
    heroImage: "assets/images/advent-lift.png",
    themeColor: "hsl(210, 60%, 14%)",
    tagline: "Step inside. The North Pole is closer than you think.",
    description: "Not a film — a world. A custom-engineered immersive Christmas elevator transports 6–8 visitors on a 3-minute journey to the North Pole using spatial audio, synchronised LED lighting, fog machines, and a cinematic video experience. Studio Varaždin designed everything: the narrative, the automation system, the set construction specifications, and the sensory choreography. One of Advent u Varaždinu 2024's most-shared attractions.",
    awards: ["Most Innovative Experience 2024"],
    featured: true,
    badges: ["Immersive", "Interactive", "Physical Installation"],
    youtubeUrl: null
  },
  {
    id: "stefany-2025",
    title: "Otrov i Med",
    subtitle: "Music Video — Stefany",
    year: 2025,
    client: "Stefany",
    category: "music-video",
    type: "Music Video",
    duration: "3:07 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/Stefany - Otrov i med.webp",
    heroImage: "assets/images/Stefany - Otrov i med.webp",
    themeColor: "hsl(345, 55%, 16%)",
    tagline: "Two worlds. One truth. No survivors.",
    description: "A conceptually sophisticated music video dissecting the anatomy of a toxic relationship through dual visual worlds: the glamorous seduction of a golden art-deco bar and the raw emotional truth of a crimson-flooded studio. Precise match-cuts stitch both worlds together as the gloss peels away, until only Stefany stands alone in the circle of red light — looking directly into the camera.",
    awards: [],
    featured: false,
    badges: ["Music Video", "Dual-World Narrative", "2025"],
    youtubeUrl: null
  },

  {
    id: "gymnasium-2024",
    title: "Prva Gimnazija Varaždin",
    subtitle: "School Portrait Film",
    year: 2024,
    client: "Prva Gimnazija Varaždin",
    category: "institutional",
    type: "Institutional Portrait Film",
    duration: "~4 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/prva-gimnazija.webp",
    heroImage: "assets/images/prva-gimnazija.webp",
    themeColor: "hsl(195, 50%, 18%)",
    tagline: "In Varaždin's oldest school, everyone is first at something.",
    description: "A time-reversal narrative following student Elizaveta through a single extraordinary day at Croatia's most storied high school. Chemistry experiments explode; an Olympian codes in the glow of a monitor; debaters spar in three languages; a sprinter blurs past on the athletics track. The final reveal: the entire film was directed by the school's own film club — a perfect meta-loop of creativity discovering itself.",
    awards: [],
    featured: false,
    badges: ["School Portrait", "Narrative", "Meta-Twist"],
    youtubeUrl: "https://www.youtube.com/watch?v=XhEGSq9XxzY"
  },
  {
    id: "fvd-2024",
    title: "Festival Varaždinskih Dvorišta",
    subtitle: "Najava 2024",
    year: 2024,
    client: "Varaždin Tourist Board",
    category: "festival",
    type: "Festival Promo",
    duration: "1:33 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/festival-dvorista-zivpotinje.webp",
    heroImage: "assets/images/festival-dvorista-zivpotinje.webp",
    themeColor: "hsl(25, 60%, 25%)",
    tagline: "Skrivena čarolija sjevera.",
    description: "Visokoproducirana najava festivala koja integrira napredne vizualne efekte za naglašavanje magične atmosfere skrivenih prostora. Emotivnom naracijom gledatelja se uvodi u jedinstven svijet varaždinskih dvorišta te predstavlja umjetnost, prirodu i zabavu skrivenih kutaka grada.",
    awards: [],
    featured: false,
    badges: ["VFX", "Narration", "Festival Promo"],
    youtubeUrl: "https://youtu.be/1DMMGhfAQTg"
  },
  {
    id: "djeda-mraza-2023",
    title: "Čarobni Grad Djeda Mraza",
    subtitle: "Advent Attraction",
    year: 2023,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Destination Promo",
    duration: "~1 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/carobni-grad-djeda-mraza.webp",
    heroImage: "assets/images/carobni-grad-djeda-mraza.webp",
    themeColor: "hsl(350, 50%, 25%)",
    tagline: "Gdje božićna magija postaje stvarnost.",
    description: "Vizualno bogat prikaz Čarobnog grada Djeda Mraza, centralne atrakcije varaždinskog Adventa. Kroz tople, kinematografske kadrove osjećaj zimske čarolije prenosi se na ekran, hvatajući autentične trenutke dječje radosti i blagdanskog duha u srcu grada.",
    awards: [],
    featured: false,
    badges: ["Christmas", "Destination", "Promo"],
    youtubeUrl: "https://www.youtube.com/watch?v=P7d4qStTvhE"
  },
  {
    id: "foi-dan-fakulteta-2023",
    title: "FOI Dan Fakulteta",
    subtitle: "Faculty of Organization and Informatics",
    year: 2023,
    client: "FOI",
    category: "event",
    type: "Event Film",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/foi-dan-fakulteta.webp",
    heroImage: "assets/images/foi-dan-fakulteta.webp",
    themeColor: "hsl(220, 45%, 25%)",
    tagline: "Gdje tradicija susreće tehnologiju budućnosti.",
    description: "Dinamičan pregled Dana fakulteta FOI-ja iz 2023. godine. Kroz brzu montažu i moderno kadriranje, video hvata akademsku atmosferu, svečane trenutke i neizostavan duh informatičke izvrsnosti koji prožima ovu instituciju.",
    awards: [],
    featured: false,
    badges: ["University", "Event", "Education"],
    youtubeUrl: "https://www.youtube.com/watch?v=BUgVrl34Txs"
  },
  {
    id: "choncha-kickstarter",
    title: "CHONCHA",
    subtitle: "Kickstarter Campaign Video",
    year: 2023,
    client: "Choncha",
    category: "campaign",
    type: "Crowdfunding Campaign",
    duration: "~3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "assets/images/choncha.webp",
    heroImage: "assets/images/choncha.webp",
    themeColor: "hsl(15, 55%, 35%)",
    tagline: "Oživite svoje biljke uz pametnu njegu.",
    description: "Visokoenergetski promo video za Choncha Kickstarter kampanju. Fokusirajući se na inovativan dizajn i funkcionalnost pametne tegle, video spaja čistu estetiku, jasnu prezentaciju proizvoda i poziv na akciju koji je pokrenuo uspješno financiranje.",
    awards: [],
    featured: false,
    badges: ["Kickstarter", "Product Design", "Campaign"],
    youtubeUrl: "https://youtu.be/965QHiMWenk"
  }
];

// Category row definitions — order matters
const ROWS = [
  { id: "documentary",  label: "Documentary & Portrait Films",  filter: p => ["documentary"].includes(p.category) },
  { id: "immersive",    label: "Immersive Experiences",          filter: p => p.category === "immersive" },
  { id: "short-film",   label: "Historical Drama & Short Films", filter: p => p.category === "short-film" },
  { id: "festival",     label: "Festival & Event Films",         filter: p => ["festival", "event"].includes(p.category) },
  { id: "music-video",  label: "Music Videos",                   filter: p => p.category === "music-video" },
  { id: "institutional",label: "Institutional & Campaign",       filter: p => ["institutional", "campaign"].includes(p.category) },
];

// Featured projects for hero rotation (in order)
const FEATURED = PROJECTS.filter(p => p.featured);
