// Studio Varaždin — Project Data (ES Module)

export const PROJECTS = [
  {
    id: "advent-varazdin-2024",
    title: "Advent u Varaždinu",
    subtitle: "Aftermovie 2024",
    year: 2024,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Festival Aftermovie",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/advent u varazdinu.webp",
    heroImage: "/assets/images/advent u varazdinu.webp",
    themeColor: "hsl(205, 55%, 20%)",
    tagline: "Where winter warmth outshines the cold.",
    description: "The official aftermovie for the multi-award-winning Advent u Varaždinu 2024. Capturing the singular magic of Croatia's most romantic winter destination, the film weaves through glowing baroque streets, the kinetic energy of the Advent Lift, and the genuine warmth of a city in celebration. A cinematic postcard of light and laughter.",
    awards: [],
    featured: false,
    badges: ["Christmas", "Aftermovie", "Destination Film"],
    youtubeUrl: "https://www.youtube.com/watch?v=1HRTf8t3RQo"
  },
  {
    id: "rimac-fpv",
    title: "Rimac Automobili",
    subtitle: "One-Take FPV Tour",
    year: 2024,
    client: "Rimac Automobili",
    category: "immersive",
    type: "FPV Drone Tour",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "FPV Drone Team"],
    thumbnail: "/assets/images/rimac.webp",
    heroImage: "/assets/images/rimac.webp",
    themeColor: "hsl(215, 60%, 15%)",
    tagline: "Precision built for the edge of the impossible.",
    description: "An adrenaline-fueled, single-take FPV drone flight through the heart of Rimac Automobili. Weaving through hypercar assembly lines, engineering labs, and production halls, the film captures the relentless energy and technological precision of Croatia's automotive future in one unbroken, cinematic movement.",
    awards: [],
    featured: false,
    badges: ["FPV", "One-Take", "Hypercar"],
    youtubeUrl: "https://www.youtube.com/watch?v=UhCaWGTM69o"
  },
  {
    id: "spancirfest-2023",
    title: "Špancirfest",
    subtitle: "25th Anniversary Aftermovie",
    year: 2023,
    client: "Varaždin Tourist Board",
    category: "festival",
    type: "Festival Aftermovie",
    duration: "7 min",
    director: "Timon Terzić",
    team: ["Dario Mikulek", "Dorian Domiter", "Sven Danko", "Ivica Hozmec", "Luka Ivić", "Stella Grbec"],
    thumbnail: "/assets/images/spancirfest.png",
    heroImage: "/assets/images/spancirfest.png",
    themeColor: "hsl(38, 70%, 25%)",
    tagline: "A city. Ten days. Four stories.",
    description: "For the 25th anniversary of Croatia's largest street festival, Studio Varaždin crafted a seven-minute multi-narrative cinematic experience. Four interlocking human stories — a lost child, a sketching artist, a young couple, a street musician — unfold against the baroque splendour of Varaždin. The festival itself becomes a fifth protagonist, alive with butterfly ornaments, fire performers, and the electric energy of a city in celebration.",
    awards: ["Festival Special Commission"],
    featured: true,
    badges: ["25th Edition", "Multi-Narrative", "Festival Film"]
  },
  {
    id: "advent-varazdin-2023",
    title: "Advent u Varaždinu",
    subtitle: "Christmas City Film",
    year: 2023,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Destination Film",
    duration: "3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/advent-varazdin.png",
    heroImage: "/assets/images/advent-varazdin.png",
    themeColor: "hsl(200, 45%, 18%)",
    tagline: "A letter to Santa. A city that writes back.",
    description: "A cinematic destination film for Varaždin's multi-award-winning Christmas market, told through a child's searching letter to Santa Claus. As lanterns glow and snowflakes fall over the baroque city, the narration asks whether magic is still real — and the city's warmth answers. One of northern Croatia's most emotionally resonant pieces of destination content.",
    awards: ["Best Christmas Destination Content"],
    featured: false,
    badges: ["Award-Winning Market", "Christmas", "Destination Film"]
  },
  {
    id: "vudrag-zeiss-2024",
    title: "VUDRAG × ZEISS",
    subtitle: "Sessions: Maker Portrait",
    year: 2024,
    client: "Zeiss Industrial Quality Solutions",
    category: "documentary",
    type: "Documentary Portrait",
    duration: "3:20 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/vudrag.png",
    heroImage: "/assets/images/vudrag.png",
    themeColor: "hsl(30, 60%, 20%)",
    tagline: "Metal is more than material. It's life forged in fire.",
    description: "A prestige co-production with Zeiss Industrial Quality Solutions for their global Maker Portrait series. The film follows Croatian sculptor Nikola Vudrag from sketching table to fire-lit workshop to precision 3D scanning — a meditation on the relationship between brute force and delicate technology, and the enduring question of legacy. Shot with ZEISS cinema glass to international production standards.",
    awards: ["International Co-Production"],
    featured: true,
    badges: ["ZEISS Partnership", "Documentary", "International"]
  },
  {
    id: "advent-lift-2024",
    title: "The Advent Lift",
    subtitle: "Journey to the North Pole",
    year: 2024,
    client: "Varaždin Tourist Board",
    category: "immersive",
    type: "Immersive Physical Experience",
    duration: "3 min live",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Hrvoje Hegedušić"],
    thumbnail: "/assets/images/advent-lift.png",
    heroImage: "/assets/images/advent-lift.png",
    themeColor: "hsl(210, 60%, 14%)",
    tagline: "Step inside. The North Pole is closer than you think.",
    description: "Not a film — a world. A custom-engineered immersive Christmas elevator transports 6–8 visitors on a 3-minute journey to the North Pole using spatial audio, synchronised LED lighting, fog machines, and a cinematic video experience. Studio Varaždin designed everything: the narrative, the automation system, the set construction specifications, and the sensory choreography. One of Advent u Varaždinu 2024's most-shared attractions.",
    awards: ["Most Innovative Experience 2024"],
    featured: true,
    badges: ["Immersive", "Interactive", "Physical Installation"]
  },
  {
    id: "ivanec-2024",
    title: "Ivanec — Zagrljaj Ivanščice",
    subtitle: "Cinematic Destination Film",
    year: 2024,
    client: "Grad Ivanec / HPD Ivančica",
    category: "documentary",
    type: "Destination Film",
    duration: "~8 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Kristijan Petrović (narrator)", "Ljiljana Risek (script)"],
    thumbnail: "/assets/images/ivanec.png",
    heroImage: "/assets/images/ivanec.png",
    themeColor: "hsl(145, 40%, 14%)",
    tagline: "Every mountain holds a story older than its name.",
    description: "A layered cinematic journey through the Ivanec region, framed as a historian-detective uncovering millennia of stories embedded in the landscape of Ivanščica mountain. Roman legions, Slavic forest spirits, medieval ruins — the film weaves AI-generated matte paintings, orthomosaic archaeological reconstructions, and FPV drone poetry into a deeply literary portrait. Narrated with poetic precision by actor Kristijan Petrović.",
    awards: [],
    featured: false,
    badges: ["Historical", "AI-Augmented", "Landscape"]
  },
  {
    id: "mint-2024",
    title: "Hrvatska Kovnica Novca",
    subtitle: "Croatian Mint — Story Film",
    year: 2024,
    client: "Hrvatska Kovnica Novca",
    category: "institutional",
    type: "Institutional Documentary",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/kovnica novca.webp",
    heroImage: "/assets/images/kovnica novca.webp",
    themeColor: "hsl(43, 75%, 22%)",
    tagline: "Every coin is a piece of history, struck for eternity.",
    description: "A prestigious production for Croatia's national mint — a story film spanning past, present, and future, produced with original score composition, professional narration, and custom VFX/CGI sequences. The film treats coin-minting as an act of national memory-keeping, giving weight and emotional resonance to limited-edition Euro and commemorative coin collections.",
    awards: [],
    featured: false,
    badges: ["National Institution", "Prestige", "VFX/CGI"]
  },

  {
    id: "gymnasium-2024",
    title: "Prva Gimnazija Varaždin",
    subtitle: "School Portrait Film",
    year: 2024,
    client: "Prva Gimnazija Varaždin",
    category: "institutional",
    type: "Institutional Portrait Film",
    duration: "~4 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/prva-gimnazija.webp",
    heroImage: "/assets/images/prva-gimnazija.webp",
    themeColor: "hsl(195, 50%, 18%)",
    tagline: "In Varaždin's oldest school, everyone is first at something.",
    description: "A time-reversal narrative following student Elizaveta through a single extraordinary day at Croatia's most storied high school. Chemistry experiments explode; an Olympian codes in the glow of a monitor; debaters spar in three languages; a sprinter blurs past on the athletics track. The final reveal: the entire film was directed by the school's own film club — a perfect meta-loop of creativity discovering itself.",
    awards: [],
    featured: false,
    badges: ["School Portrait", "Narrative", "Meta-Twist"],
    youtubeUrl: "https://www.youtube.com/watch?v=XhEGSq9XxzY"
  },
  {
    id: "stefany-2025",
    title: "Otrov i Med",
    subtitle: "Music Video — Stefany",
    year: 2025,
    client: "Stefany",
    category: "music-video",
    type: "Music Video",
    duration: "3:07 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/stefany.png",
    heroImage: "/assets/images/stefany.png",
    themeColor: "hsl(345, 55%, 16%)",
    tagline: "Two worlds. One truth. No survivors.",
    description: "A conceptually sophisticated music video dissecting the anatomy of a toxic relationship through dual visual worlds: the glamorous seduction of a golden art-deco bar and the raw emotional truth of a crimson-flooded studio. Precise match-cuts stitch both worlds together as the gloss peels away, until only Stefany stands alone in the circle of red light — looking directly into the camera.",
    awards: [],
    featured: true,
    badges: ["Music Video", "Dual-World Narrative", "2025"]
  },
  {
    id: "trakostyan-2025",
    title: "Glasnik Vječnosti",
    subtitle: "Trakostyan Tours — Historical Film",
    year: 2025,
    client: "Trakostyan-Tours",
    category: "short-film",
    type: "Historical Cinematic Short",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "15+ period performers", "Live falcon & falconer"],
    thumbnail: "/assets/images/trakostyan.png",
    heroImage: "/assets/images/trakostyan.png",
    themeColor: "hsl(148, 38%, 10%)",
    tagline: "Kingdoms fall. Stories endure.",
    description: "Three eras. Three locations. One eternal witness. Glasnik Vječnosti (Messenger of Eternity) weaves Roman mythology, medieval intrigue, and baroque court drama through the thread of a falcon's flight — from the ruins of Varaždinske Toplice to the towers of Trakošćan castle to the baroque skyline of Varaždin. Featuring over fifteen costumed performers, a live trained falcon, and three consecutive production days across northern Croatia.",
    awards: ["Tourism Film of the Year Nomination"],
    featured: true,
    badges: ["Epic Historical", "3 Eras", "Live Falcon"]
  },
  {
    id: "castles-2025",
    title: "100 Dvoraca Sjevera Hrvatske",
    subtitle: "A Fairytale Film",
    year: 2025,
    client: "Castle Network of Northern Croatia",
    category: "short-film",
    type: "Cinematic Short / Drama",
    duration: "~15 min",
    director: "Timon Terzić",
    team: ["Timon Terzić", "Full cast & crew"],
    thumbnail: "/assets/images/100-castles.png",
    heroImage: "/assets/images/100-castles.png",
    themeColor: "hsl(40, 55%, 18%)",
    tagline: "Every page turns a legend into life.",
    description: "A fairytale-structured short film following ten-year-old Ema and her mother as a magical pop-up book transports them into the love stories of northern Croatia's castles. At Trakošćan, a knight rides off to war; at Veliki Tabor, a feudal lord falls for a peasant girl; at the Varaždin citadel, time defeats a love too patient to survive it; at Čakovec, a family's warmth fills the courtyard with mud and laughter.",
    awards: [],
    featured: false,
    badges: ["In Production", "Fairytale Drama", "Castles"]
  },
  {
    id: "fvd-2024",
    title: "Festival Varaždinskih Dvorišta",
    subtitle: "Najava 2024",
    year: 2024,
    client: "Varaždin Tourist Board",
    category: "festival",
    type: "Festival Promo",
    duration: "1:33 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/festival-dvorista-zivpotinje.webp",
    heroImage: "/assets/images/festival-dvorista-zivpotinje.webp",
    themeColor: "hsl(25, 60%, 25%)",
    tagline: "Skrivena čarolija sjevera.",
    description: "Visokoproducirana najava festivala koja integrira napredne vizualne efekte za naglašavanje magične atmosfere skrivenih prostora. Emotivnom naracijom gledatelja se uvodi u jedinstven svijet varaždinskih dvorišta te predstavlja umjetnost, prirodu i zabavu skrivenih kutaka grada.",
    awards: [],
    featured: false,
    badges: ["VFX", "Narration", "Festival Promo"],
    youtubeUrl: "https://youtu.be/1DMMGhfAQTg"
  },
  {
    id: "djeda-mraza-2023",
    title: "Čarobni Grad Djeda Mraza",
    subtitle: "Advent Attraction",
    year: 2023,
    client: "Varaždin Tourist Board",
    category: "event",
    type: "Destination Promo",
    duration: "~1 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/carobni-grad-djeda-mraza.webp",
    heroImage: "/assets/images/carobni-grad-djeda-mraza.webp",
    themeColor: "hsl(350, 50%, 25%)",
    tagline: "Gdje božićna magija postaje stvarnost.",
    description: "Vizualno bogat prikaz Čarobnog grada Djeda Mraza, centralne atrakcije varaždinskog Adventa. Kroz tople, kinematografske kadrove osjećaj zimske čarolije prenosi se na ekran, hvatajući autentične trenutke dječje radosti i blagdanskog duha u srcu grada.",
    awards: [],
    featured: false,
    badges: ["Christmas", "Destination", "Promo"]
  },
  {
    id: "foi-dan-fakulteta-2023",
    title: "FOI Dan Fakulteta",
    subtitle: "Faculty of Organization and Informatics",
    year: 2023,
    client: "FOI",
    category: "event",
    type: "Event Film",
    duration: "~2 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/foi-dan-fakulteta.webp",
    heroImage: "/assets/images/foi-dan-fakulteta.webp",
    themeColor: "hsl(220, 45%, 25%)",
    tagline: "Gdje tradicija susreće tehnologiju budućnosti.",
    description: "Dinamičan pregled Dana fakulteta FOI-ja iz 2023. godine. Kroz brzu montažu i moderno kadriranje, video hvata akademsku atmosferu, svečane trenutke i neizostavan duh informatičke izvrsnosti koji prožima ovu instituciju.",
    awards: [],
    featured: false,
    badges: ["University", "Event", "Education"],
    youtubeUrl: "https://www.youtube.com/watch?v=BUgVrl34Txs"
  },
  {
    id: "choncha-kickstarter",
    title: "CHONCHA",
    subtitle: "Kickstarter Campaign Video",
    year: 2023,
    client: "Choncha",
    category: "campaign",
    type: "Crowdfunding Campaign",
    duration: "~3 min",
    director: "Timon Terzić",
    team: ["Timon Terzić"],
    thumbnail: "/assets/images/choncha.webp",
    heroImage: "/assets/images/choncha.webp",
    themeColor: "hsl(15, 55%, 35%)",
    tagline: "Oživite svoje biljke uz pametnu njegu.",
    description: "Visokoenergetski promo video za Choncha Kickstarter kampanju. Fokusirajući se na inovativan dizajn i funkcionalnost pametne tegle, video spaja čistu estetiku, jasnu prezentaciju proizvoda i poziv na akciju koji je pokrenuo uspješno financiranje.",
    awards: [],
    featured: false,
    badges: ["Kickstarter", "Product Design", "Campaign"],
    youtubeUrl: "https://youtu.be/965QHiMWenk"
  }
];

// Category row definitions — order matters
export const ROWS = [
  { id: "documentary",   label: "Documentary & Portrait Films",   filter: p => ["documentary"].includes(p.category) },
  { id: "immersive",     label: "Immersive Experiences",          filter: p => p.category === "immersive" },
  { id: "short-film",    label: "Historical Drama & Short Films", filter: p => p.category === "short-film" },
  { id: "festival",      label: "Festival & Event Films",         filter: p => ["festival", "event"].includes(p.category) },
  { id: "music-video",   label: "Music Videos",                   filter: p => p.category === "music-video" },
  { id: "institutional", label: "Institutional & Campaign",       filter: p => ["institutional", "campaign"].includes(p.category) },
];

// Featured projects for hero rotation
export const FEATURED = PROJECTS.filter(p => p.featured);
